### ISSUE TITLE
Error while generating otp 

### ISSUE THREAD

**Issue by Advaitgaur004** [wasim395/OJ_Project_394#2]
![image](https://github.com/wasim395/OJ_Project_394/assets/126783821/d1c25d3d-eb0e-4852-b7dc-5d9290f79a86)
Error in Requesting OTP...resolve this (will take 5 min) 

@wasim395

**Comment by wasim395** [comment]
The password must be at least 6 characters long. That is why this error is showing.

**Comment by Advaitgaur004** [comment]
okay nice, just use validator in frontend so that it wont sent query to server side for processing and Display any error message in alert or any format you wannted
